/**
 * Installs OMX assets (prompts, skills, agents) into a provider's
 * directory structure, translating formats as needed.
 */

import { existsSync } from "fs";
import { mkdir, copyFile, readFile, writeFile, readdir } from "fs/promises";
import { join, basename } from "path";
import {
  type Provider,
  type ProviderName,
  getProvider,
} from "./providers.js";
import {
  resolveOmxRoot,
  listOmxPrompts,
  listOmxSkills,
  listOmxAgents,
} from "./resolver.js";

export interface InstallOptions {
  provider: ProviderName;
  /** Install to project-local dir instead of user home */
  projectLocal?: boolean;
  /** Project root (defaults to cwd) */
  projectRoot?: string;
  /** Show detailed output */
  verbose?: boolean;
  /** Show what would happen without doing it */
  dryRun?: boolean;
}

export interface InstallResult {
  provider: ProviderName;
  targetDir: string;
  prompts: { installed: number; skipped: number };
  skills: { installed: number; skipped: number };
  promptInjection: { file?: string; status: string };
}

/**
 * Install OMX assets into the target provider's directories.
 */
export async function install(options: InstallOptions): Promise<InstallResult> {
  const {
    provider: providerName,
    projectLocal = false,
    projectRoot = process.cwd(),
    verbose = false,
    dryRun = false,
  } = options;

  const provider = getProvider(providerName);
  const omxRoot = resolveOmxRoot();

  // Determine target directory
  const targetDir = projectLocal
    ? join(projectRoot, provider.projectDirName)
    : provider.homeDir;

  const promptsTarget = join(targetDir, provider.promptsDir);
  const skillsTarget = join(targetDir, provider.skillsDir);

  // Ensure directories
  if (!dryRun) {
    await mkdir(promptsTarget, { recursive: true });
    await mkdir(skillsTarget, { recursive: true });
  }
  if (verbose) {
    console.log(`  Target: ${targetDir}`);
    console.log(`  Prompts: ${promptsTarget}`);
    console.log(`  Skills: ${skillsTarget}`);
  }

  // Copy prompts
  const promptFiles = await listOmxPrompts(omxRoot);
  let promptsInstalled = 0;
  let promptsSkipped = 0;
  for (const src of promptFiles) {
    const dest = join(promptsTarget, basename(src));
    if (existsSync(dest)) {
      const [srcContent, destContent] = await Promise.all([
        readFile(src, "utf-8"),
        readFile(dest, "utf-8"),
      ]);
      if (srcContent === destContent) {
        promptsSkipped++;
        continue;
      }
    }
    if (!dryRun) {
      await copyFile(src, dest);
    }
    promptsInstalled++;
    if (verbose) console.log(`  ${dryRun ? "would copy" : "copied"} ${basename(src)}`);
  }

  // Copy skills
  const skills = await listOmxSkills(omxRoot);
  let skillsInstalled = 0;
  let skillsSkipped = 0;
  for (const skill of skills) {
    const destDir = join(skillsTarget, skill.name);
    if (!dryRun) {
      await mkdir(destDir, { recursive: true });
    }
    const files = await readdir(skill.path);
    let anyChanged = false;
    for (const file of files) {
      const src = join(skill.path, file);
      const dest = join(destDir, file);
      if (existsSync(dest)) {
        const [srcContent, destContent] = await Promise.all([
          readFile(src, "utf-8"),
          readFile(dest, "utf-8"),
        ]);
        if (srcContent === destContent) continue;
      }
      if (!dryRun) {
        await copyFile(src, dest);
      }
      anyChanged = true;
    }
    if (anyChanged) {
      skillsInstalled++;
      if (verbose) console.log(`  ${dryRun ? "would install" : "installed"} skill: ${skill.name}`);
    } else {
      skillsSkipped++;
    }
  }

  // Generate prompt injection file
  const injectionResult = await generatePromptInjection(
    provider,
    omxRoot,
    projectLocal ? projectRoot : targetDir,
    { verbose, dryRun },
  );

  return {
    provider: providerName,
    targetDir,
    prompts: { installed: promptsInstalled, skipped: promptsSkipped },
    skills: { installed: skillsInstalled, skipped: skillsSkipped },
    promptInjection: injectionResult,
  };
}

/**
 * Generate the prompt injection artifact for the given provider.
 */
async function generatePromptInjection(
  provider: Provider,
  omxRoot: string,
  targetRoot: string,
  options: { verbose?: boolean; dryRun?: boolean },
): Promise<{ file?: string; status: string }> {
  const injection = provider.promptInjection;

  // Build a combined markdown/rules file from all OMX agent prompts
  const agents = await listOmxAgents(omxRoot);
  const sections: string[] = [
    `# OMX Agent Prompts`,
    ``,
    `> Auto-generated by omx-provider. Do not edit manually.`,
    `> Source: oh-my-codex prompts`,
    ``,
  ];

  for (const agent of agents) {
    const content = await readFile(agent.path, "utf-8");
    sections.push(`## ${agent.name}`);
    sections.push("");
    sections.push(content);
    sections.push("");
  }

  const filename = injection.filename;
  const filePath = join(targetRoot, filename);

  // If file exists, check for OMX marker before overwriting
  if (existsSync(filePath)) {
    const existing = await readFile(filePath, "utf-8");
    if (!existing.includes("Auto-generated by omx-provider")) {
      if (options.verbose) {
        console.log(`  Skipping ${filename}: file exists and was not generated by omx-provider`);
      }
      return { file: filePath, status: "skipped (user-owned file)" };
    }
  }

  if (!options.dryRun) {
    await writeFile(filePath, sections.join("\n"));
  }
  if (options.verbose) {
    console.log(`  ${options.dryRun ? "would write" : "wrote"} ${filename} (${agents.length} agents)`);
  }
  return { file: filePath, status: "written" };
}
