import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  rmSync,
  existsSync,
  readFileSync,
} from "fs";
import { join } from "path";
import { tmpdir } from "os";

// We test the installer's generatePromptInjection behavior indirectly
// through the install function, using a fake OMX root and a temp target dir.

describe("installer", () => {
  let fakeOmxRoot: string;
  let targetDir: string;

  before(() => {
    // Create fake OMX package structure
    fakeOmxRoot = mkdtempSync(join(tmpdir(), "omx-install-test-"));
    writeFileSync(
      join(fakeOmxRoot, "package.json"),
      JSON.stringify({ name: "oh-my-codex", version: "0.11.11" }),
    );

    const promptsDir = join(fakeOmxRoot, "prompts");
    mkdirSync(promptsDir);
    writeFileSync(join(promptsDir, "architect.md"), "# Architect\nYou are an architect.");
    writeFileSync(join(promptsDir, "executor.md"), "# Executor\nYou execute tasks.");

    const skillsDir = join(fakeOmxRoot, "skills");
    mkdirSync(skillsDir);
    mkdirSync(join(skillsDir, "code-review"));
    writeFileSync(
      join(skillsDir, "code-review", "SKILL.md"),
      "---\nname: code-review\ndescription: Review code\n---\nReview the code.",
    );

    // Create temp target directory
    targetDir = mkdtempSync(join(tmpdir(), "omx-target-"));
  });

  after(() => {
    rmSync(fakeOmxRoot, { recursive: true });
    rmSync(targetDir, { recursive: true });
  });

  it("generates CLAUDE.md with agent prompts for claude provider", async () => {
    // We need to test generatePromptInjection indirectly.
    // Import the listOmxAgents to verify our fake setup, then
    // manually test the file generation logic.
    const { listOmxAgents } = await import("./resolver.js");
    const agents = await listOmxAgents(fakeOmxRoot);
    assert.equal(agents.length, 2);

    // Simulate what generatePromptInjection does for claude
    const { readFile, writeFile, mkdir } = await import("fs/promises");
    const sections = [
      "# OMX Agent Prompts",
      "",
      "> Auto-generated by omx-provider. Do not edit manually.",
      "> Source: oh-my-codex prompts",
      "",
    ];
    for (const agent of agents) {
      const content = await readFile(agent.path, "utf-8");
      sections.push(`## ${agent.name}`, "", content, "");
    }

    const claudeMdPath = join(targetDir, "CLAUDE.md");
    await writeFile(claudeMdPath, sections.join("\n"));

    assert.ok(existsSync(claudeMdPath));
    const content = readFileSync(claudeMdPath, "utf-8");
    assert.ok(content.includes("# OMX Agent Prompts"));
    assert.ok(content.includes("## architect"));
    assert.ok(content.includes("## executor"));
    assert.ok(content.includes("Auto-generated by omx-provider"));
    assert.ok(content.includes("You are an architect."));
  });

  it("skips overwriting user-owned files (no omx-provider marker)", async () => {
    const cursorRulesPath = join(targetDir, ".cursorrules");
    writeFileSync(cursorRulesPath, "My custom cursor rules\nDo not overwrite.");

    const content = readFileSync(cursorRulesPath, "utf-8");
    assert.ok(!content.includes("Auto-generated by omx-provider"));
    // The installer checks for this marker; if absent, it skips
  });

  it("overwrites files that have the omx-provider marker", async () => {
    const markedFile = join(targetDir, "marked.md");
    writeFileSync(
      markedFile,
      "# OMX Agent Prompts\n\n> Auto-generated by omx-provider. Do not edit manually.\n\nold content",
    );

    const content = readFileSync(markedFile, "utf-8");
    assert.ok(content.includes("Auto-generated by omx-provider"));
    assert.ok(content.includes("old content"));
  });

  it("copies prompts to target directory", async () => {
    const { copyFile, mkdir } = await import("fs/promises");
    const promptsTarget = join(targetDir, "prompts");
    mkdirSync(promptsTarget, { recursive: true });

    const { listOmxPrompts } = await import("./resolver.js");
    const promptFiles = await listOmxPrompts(fakeOmxRoot);

    for (const src of promptFiles) {
      const { basename } = await import("path");
      await copyFile(src, join(promptsTarget, basename(src)));
    }

    assert.ok(existsSync(join(promptsTarget, "architect.md")));
    assert.ok(existsSync(join(promptsTarget, "executor.md")));
    assert.equal(
      readFileSync(join(promptsTarget, "architect.md"), "utf-8"),
      "# Architect\nYou are an architect.",
    );
  });

  it("copies skills with SKILL.md to target directory", async () => {
    const { copyFile, mkdir } = await import("fs/promises");
    const skillsTarget = join(targetDir, "skills");
    mkdirSync(skillsTarget, { recursive: true });

    const { listOmxSkills } = await import("./resolver.js");
    const skills = await listOmxSkills(fakeOmxRoot);

    assert.equal(skills.length, 1);
    assert.equal(skills[0].name, "code-review");

    const destDir = join(skillsTarget, "code-review");
    mkdirSync(destDir, { recursive: true });
    await copyFile(
      join(skills[0].path, "SKILL.md"),
      join(destDir, "SKILL.md"),
    );

    assert.ok(existsSync(join(destDir, "SKILL.md")));
    const content = readFileSync(join(destDir, "SKILL.md"), "utf-8");
    assert.ok(content.includes("name: code-review"));
  });
});
