import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, existsSync, readFileSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import {
  transformPlugin,
  analyzeTransform,
  formatAnalysis,
  buildCursorContent,
  buildCodexContent,
  stripClaudeSpecificFrontmatter,
} from "./plugin-transformer.js";
import type { ParsedPlugin } from "./plugin-reader.js";

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function makePlugin(overrides?: Partial<ParsedPlugin>): ParsedPlugin {
  return {
    manifest: {
      name: "test-plugin",
      version: "1.0.0",
      description: "A test plugin for transformation",
    },
    commands: [
      {
        name: "do-thing",
        description: "Does a thing",
        argumentHint: "<arg>",
        allowedTools: "Bash(pattern:*), Read",
        body: "# Do Thing\n\nStep 1: Do it.\nStep 2: Done.",
      },
    ],
    agents: [
      {
        name: "reviewer",
        description: "Reviews code",
        tools: "Glob, Grep, Read",
        model: "sonnet",
        color: "green",
        body: "# Reviewer\n\nYou review code carefully.",
      },
    ],
    skills: [
      {
        name: "my-skill",
        description: "A skill",
        body: "# My Skill\n\nGuidelines here.",
      },
    ],
    hooks: [],
    portability: "universal",
    warnings: [],
    sourcePath: "/fake/path",
    ...overrides,
  };
}

/* ------------------------------------------------------------------ */
/*  stripClaudeSpecificFrontmatter                                     */
/* ------------------------------------------------------------------ */

describe("stripClaudeSpecificFrontmatter", () => {
  it("removes allowed-tools, model, color, tools", () => {
    const attrs = {
      description: "My command",
      "allowed-tools": "Bash, Read",
      model: "sonnet",
      color: "green",
      tools: "Glob, Grep",
      "argument-hint": "<name>",
    };
    const stripped = stripClaudeSpecificFrontmatter(attrs);
    assert.equal(stripped.description, "My command");
    assert.equal(stripped["argument-hint"], "<name>");
    assert.ok(!("allowed-tools" in stripped));
    assert.ok(!("model" in stripped));
    assert.ok(!("color" in stripped));
    assert.ok(!("tools" in stripped));
  });
});

/* ------------------------------------------------------------------ */
/*  buildCursorContent                                                 */
/* ------------------------------------------------------------------ */

describe("buildCursorContent", () => {
  it("produces valid cursor rules markdown", () => {
    const plugin = makePlugin();
    const content = buildCursorContent(plugin);

    assert.ok(content.includes("# test-plugin"));
    assert.ok(content.includes("Auto-generated by omx-provider"));
    assert.ok(content.includes("Portability: universal"));
    assert.ok(content.includes("## Commands"));
    assert.ok(content.includes("### /do-thing"));
    assert.ok(content.includes("## Agents"));
    assert.ok(content.includes("### reviewer"));
    assert.ok(content.includes("## Skills"));
    assert.ok(content.includes("### my-skill"));
  });

  it("includes portability notes for hook-based plugins", () => {
    const plugin = makePlugin({
      hooks: [{ event: "PreToolUse", scriptPath: "check.py", description: "Security" }],
      portability: "low",
      warnings: ["Plugin uses hooks"],
    });
    const content = buildCursorContent(plugin);
    assert.ok(content.includes("Portability Notes"));
    assert.ok(content.includes("PreToolUse"));
  });

  it("omits empty sections", () => {
    const plugin = makePlugin({ commands: [], agents: [] });
    const content = buildCursorContent(plugin);
    assert.ok(!content.includes("## Commands"));
    assert.ok(!content.includes("## Agents"));
    assert.ok(content.includes("## Skills"));
  });
});

/* ------------------------------------------------------------------ */
/*  buildCodexContent                                                  */
/* ------------------------------------------------------------------ */

describe("buildCodexContent", () => {
  it("produces SKILL.md with frontmatter", () => {
    const plugin = makePlugin();
    const content = buildCodexContent(plugin);

    assert.ok(content.startsWith("---\n"));
    assert.ok(content.includes("name: test-plugin"));
    assert.ok(content.includes("description: A test plugin for transformation"));
    assert.ok(content.includes("Auto-generated by omx-provider"));
  });
});

/* ------------------------------------------------------------------ */
/*  transformPlugin (integration)                                      */
/* ------------------------------------------------------------------ */

describe("transformPlugin for cursor", () => {
  let tempDir: string;

  before(() => {
    tempDir = mkdtempSync(join(tmpdir(), "transform-cursor-"));
  });

  after(() => {
    rmSync(tempDir, { recursive: true });
  });

  it("writes cursor rules file", async () => {
    const plugin = makePlugin();
    const result = await transformPlugin(plugin, {
      target: "cursor",
      outputDir: tempDir,
    });

    assert.equal(result.pluginName, "test-plugin");
    assert.equal(result.target, "cursor");
    assert.equal(result.filesWritten.length, 1);
    assert.ok(result.filesWritten[0].endsWith("test-plugin.md"));

    const content = readFileSync(result.filesWritten[0], "utf-8");
    assert.ok(content.includes("# test-plugin"));
    assert.ok(content.includes("Auto-generated by omx-provider"));
  });

  it("respects dry-run mode", async () => {
    const outDir = join(tempDir, "dryrun");
    const plugin = makePlugin();
    const result = await transformPlugin(plugin, {
      target: "cursor",
      outputDir: outDir,
      dryRun: true,
    });

    assert.equal(result.filesWritten.length, 1);
    assert.ok(!existsSync(result.filesWritten[0]));
  });
});

describe("transformPlugin for codex", () => {
  let tempDir: string;

  before(() => {
    tempDir = mkdtempSync(join(tmpdir(), "transform-codex-"));
  });

  after(() => {
    rmSync(tempDir, { recursive: true });
  });

  it("writes SKILL.md file", async () => {
    const plugin = makePlugin();
    const result = await transformPlugin(plugin, {
      target: "codex",
      outputDir: tempDir,
    });

    assert.equal(result.target, "codex");
    assert.equal(result.filesWritten.length, 1);
    assert.ok(result.filesWritten[0].includes("SKILL.md"));

    const content = readFileSync(result.filesWritten[0], "utf-8");
    assert.ok(content.includes("name: test-plugin"));
  });
});

describe("transformPlugin marker protection", () => {
  let tempDir: string;

  before(() => {
    tempDir = mkdtempSync(join(tmpdir(), "transform-marker-"));

    // Create a user-owned file that should not be overwritten
    const rulesDir = join(tempDir, ".cursor", "rules");
    mkdirSync(rulesDir, { recursive: true });
    writeFileSync(
      join(rulesDir, "test-plugin.md"),
      "# My custom rules\n\nDo not overwrite.",
    );
  });

  after(() => {
    rmSync(tempDir, { recursive: true });
  });

  it("skips user-owned files", async () => {
    const plugin = makePlugin();
    const result = await transformPlugin(plugin, {
      target: "cursor",
      outputDir: tempDir,
    });

    assert.equal(result.filesWritten.length, 0);
    assert.ok(result.warnings.some((w) => w.includes("user-owned")));

    // Verify original content preserved
    const content = readFileSync(
      join(tempDir, ".cursor", "rules", "test-plugin.md"),
      "utf-8",
    );
    assert.ok(content.includes("My custom rules"));
  });

  it("overwrites omx-generated files", async () => {
    // Write an omx-generated file
    const rulesDir = join(tempDir, ".cursor", "rules");
    writeFileSync(
      join(rulesDir, "overwrite-me.md"),
      "# old\n\n> Auto-generated by omx-provider.\n\nOld content.",
    );

    const plugin = makePlugin({
      manifest: {
        name: "overwrite-me",
        version: "1.0.0",
        description: "Should overwrite",
      },
    });
    const result = await transformPlugin(plugin, {
      target: "cursor",
      outputDir: tempDir,
    });

    assert.equal(result.filesWritten.length, 1);
    const content = readFileSync(result.filesWritten[0], "utf-8");
    assert.ok(content.includes("Should overwrite"));
  });
});

describe("transformPlugin for claude", () => {
  let tempDir: string;

  before(() => {
    tempDir = mkdtempSync(join(tmpdir(), "transform-claude-"));
  });

  after(() => {
    rmSync(tempDir, { recursive: true });
  });

  it("writes skill directory", async () => {
    const plugin = makePlugin();
    const result = await transformPlugin(plugin, {
      target: "claude",
      outputDir: tempDir,
    });

    assert.equal(result.target, "claude");
    assert.equal(result.filesWritten.length, 1);
    assert.ok(result.filesWritten[0].includes("SKILL.md"));
  });
});

/* ------------------------------------------------------------------ */
/*  analyzeTransform                                                   */
/* ------------------------------------------------------------------ */

describe("analyzeTransform", () => {
  let tempDir: string;

  before(() => {
    tempDir = mkdtempSync(join(tmpdir(), "analyze-"));

    // Pre-create a user-owned file for one plugin
    const rulesDir = join(tempDir, ".cursor", "rules");
    mkdirSync(rulesDir, { recursive: true });
    writeFileSync(
      join(rulesDir, "existing-plugin.md"),
      "# My rules\n\nUser-owned.",
    );

    // Pre-create an omx-generated file for another
    writeFileSync(
      join(rulesDir, "updatable-plugin.md"),
      "# Old\n\n> Auto-generated by omx-provider.\n\nOld content.",
    );
  });

  after(() => {
    rmSync(tempDir, { recursive: true });
  });

  it("detects new plugins as 'create'", () => {
    const plugins = [makePlugin({ manifest: { name: "brand-new", version: "1.0.0", description: "New" } })];
    const analysis = analyzeTransform(plugins, "cursor", tempDir);

    assert.equal(analysis.plugins.length, 1);
    assert.equal(analysis.plugins[0].action, "create");
    assert.equal(analysis.summary.create, 1);
    assert.equal(analysis.summary.update, 0);
    assert.equal(analysis.summary.skip, 0);
  });

  it("detects user-owned files as 'skip'", () => {
    const plugins = [makePlugin({ manifest: { name: "existing-plugin", version: "1.0.0", description: "Existing" } })];
    const analysis = analyzeTransform(plugins, "cursor", tempDir);

    assert.equal(analysis.plugins[0].action, "skip (user-owned)");
    assert.equal(analysis.summary.skip, 1);
  });

  it("detects omx-generated files as 'update'", () => {
    const plugins = [makePlugin({ manifest: { name: "updatable-plugin", version: "1.0.0", description: "Update" } })];
    const analysis = analyzeTransform(plugins, "cursor", tempDir);

    assert.equal(analysis.plugins[0].action, "update");
    assert.equal(analysis.summary.update, 1);
  });

  it("counts components correctly", () => {
    const plugins = [makePlugin()];
    const analysis = analyzeTransform(plugins, "cursor", tempDir);

    assert.equal(analysis.plugins[0].components.commands, 1);
    assert.equal(analysis.plugins[0].components.agents, 1);
    assert.equal(analysis.plugins[0].components.skills, 1);
    assert.equal(analysis.plugins[0].components.hooks, 0);
  });

  it("handles mixed batch correctly", () => {
    const plugins = [
      makePlugin({ manifest: { name: "brand-new", version: "1.0.0", description: "New" } }),
      makePlugin({ manifest: { name: "existing-plugin", version: "1.0.0", description: "Existing" } }),
      makePlugin({ manifest: { name: "updatable-plugin", version: "1.0.0", description: "Update" } }),
    ];
    const analysis = analyzeTransform(plugins, "cursor", tempDir);

    assert.equal(analysis.summary.total, 3);
    assert.equal(analysis.summary.create, 1);
    assert.equal(analysis.summary.skip, 1);
    assert.equal(analysis.summary.update, 1);
  });
});

/* ------------------------------------------------------------------ */
/*  formatAnalysis                                                     */
/* ------------------------------------------------------------------ */

describe("formatAnalysis", () => {
  it("produces readable output with table and summary", () => {
    const plugins = [
      makePlugin(),
      makePlugin({
        manifest: { name: "hook-plugin", version: "1.0.0", description: "Has hooks" },
        hooks: [{ event: "PreToolUse", scriptPath: "check.py" }],
        portability: "low",
        warnings: ["Uses hooks"],
      }),
    ];
    const analysis = analyzeTransform(plugins, "cursor", join(tmpdir(), "nonexistent"));
    const output = formatAnalysis(analysis);

    assert.ok(output.includes("Analysis"));
    assert.ok(output.includes("Cursor"));
    assert.ok(output.includes("test-plugin"));
    assert.ok(output.includes("hook-plugin"));
    assert.ok(output.includes("universal"));
    assert.ok(output.includes("low"));
    assert.ok(output.includes("+ create"));
    assert.ok(output.includes("Summary:"));
    assert.ok(output.includes("Warnings:"));
    assert.ok(output.includes("Uses hooks"));
  });

  it("omits warnings section when none exist", () => {
    const plugins = [makePlugin()];
    const analysis = analyzeTransform(plugins, "cursor", join(tmpdir(), "nonexistent"));
    const output = formatAnalysis(analysis);

    assert.ok(!output.includes("Warnings:"));
  });
});
