/**
 * Transforms parsed Anthropic plugins into target platform formats
 * (Cursor rules, Codex skills, or Claude plugins).
 */

import { existsSync, readFileSync } from "fs";
import { mkdir, readFile, writeFile } from "fs/promises";
import { join } from "path";
import { type ProviderName, getProvider } from "./providers.js";
import type { ParsedPlugin, PluginCommand, PluginAgent, PluginSkill } from "./plugin-reader.js";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface TransformOptions {
  target: ProviderName;
  outputDir?: string;
  verbose?: boolean;
  dryRun?: boolean;
}

export interface TransformResult {
  pluginName: string;
  target: ProviderName;
  filesWritten: string[];
  portability: string;
  warnings: string[];
}

export type FileAction = "create" | "update" | "skip (user-owned)";

export interface PluginAnalysis {
  pluginName: string;
  portability: string;
  components: {
    commands: number;
    agents: number;
    skills: number;
    hooks: number;
  };
  targetFile: string;
  action: FileAction;
  warnings: string[];
}

export interface TransformAnalysis {
  target: ProviderName;
  outputDir: string;
  plugins: PluginAnalysis[];
  summary: {
    total: number;
    create: number;
    update: number;
    skip: number;
  };
}

const MARKER = "Auto-generated by omx-provider";

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function stripClaudeSpecificFrontmatter(
  attrs: Record<string, string>,
): Record<string, string> {
  const stripped = { ...attrs };
  delete stripped["allowed-tools"];
  delete stripped.model;
  delete stripped.color;
  delete stripped.tools;
  return stripped;
}

function renderFrontmatter(attrs: Record<string, string>): string {
  const entries = Object.entries(attrs).filter(([, v]) => v !== undefined && v !== "");
  if (entries.length === 0) return "";
  const lines = entries.map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join("\n")}\n---\n\n`;
}

function renderCommandSection(cmd: PluginCommand): string {
  const lines: string[] = [];
  lines.push(`### /${cmd.name}`);
  if (cmd.description) lines.push(`> ${cmd.description}`);
  lines.push("");
  lines.push(cmd.body.trim());
  lines.push("");
  return lines.join("\n");
}

function renderAgentSection(agent: PluginAgent): string {
  const lines: string[] = [];
  lines.push(`### ${agent.name}`);
  if (agent.description) lines.push(`> ${agent.description}`);
  lines.push("");
  lines.push(agent.body.trim());
  lines.push("");
  return lines.join("\n");
}

function renderSkillSection(skill: PluginSkill): string {
  const lines: string[] = [];
  lines.push(`### ${skill.name}`);
  if (skill.description) lines.push(`> ${skill.description}`);
  lines.push("");
  lines.push(skill.body.trim());
  lines.push("");
  return lines.join("\n");
}

function renderHookWarnings(plugin: ParsedPlugin): string {
  if (plugin.hooks.length === 0) return "";
  const lines: string[] = [
    "## Portability Notes",
    "",
    "> The following features relied on Claude Code hooks and are not actively enforced.",
    "> They are included as guidelines only.",
    "",
  ];
  for (const hook of plugin.hooks) {
    lines.push(`- **${hook.event}**: ${hook.description || hook.scriptPath}`);
  }
  lines.push("");
  return lines.join("\n");
}

/* ------------------------------------------------------------------ */
/*  Cursor transformer                                                 */
/* ------------------------------------------------------------------ */

function buildCursorContent(plugin: ParsedPlugin): string {
  const sections: string[] = [];

  sections.push(`# ${plugin.manifest.name}`);
  sections.push("");
  sections.push(`> ${MARKER}. Do not edit manually.`);
  sections.push(`> Source: anthropic/${plugin.manifest.name} plugin`);
  sections.push(`> Portability: ${plugin.portability}`);
  sections.push("");

  if (plugin.manifest.description) {
    sections.push(plugin.manifest.description);
    sections.push("");
  }

  if (plugin.commands.length > 0) {
    sections.push("## Commands");
    sections.push("");
    for (const cmd of plugin.commands) {
      sections.push(renderCommandSection(cmd));
    }
  }

  if (plugin.agents.length > 0) {
    sections.push("## Agents");
    sections.push("");
    for (const agent of plugin.agents) {
      sections.push(renderAgentSection(agent));
    }
  }

  if (plugin.skills.length > 0) {
    sections.push("## Skills");
    sections.push("");
    for (const skill of plugin.skills) {
      sections.push(renderSkillSection(skill));
    }
  }

  sections.push(renderHookWarnings(plugin));

  return sections.join("\n");
}

async function transformForCursor(
  plugin: ParsedPlugin,
  outputDir: string,
  options: { verbose?: boolean; dryRun?: boolean },
): Promise<TransformResult> {
  const rulesDir = join(outputDir, ".cursor", "rules");
  const filePath = join(rulesDir, `${plugin.manifest.name}.md`);
  const filesWritten: string[] = [];

  const content = buildCursorContent(plugin);

  if (!options.dryRun) {
    await mkdir(rulesDir, { recursive: true });

    if (existsSync(filePath)) {
      const existing = await readFile(filePath, "utf-8");
      if (!existing.includes(MARKER)) {
        if (options.verbose) {
          console.log(`  Skipping ${filePath}: user-owned file`);
        }
        return {
          pluginName: plugin.manifest.name,
          target: "cursor",
          filesWritten: [],
          portability: plugin.portability,
          warnings: [...plugin.warnings, "Skipped: existing user-owned file"],
        };
      }
    }

    await writeFile(filePath, content);
  }

  filesWritten.push(filePath);
  if (options.verbose) {
    console.log(`  ${options.dryRun ? "would write" : "wrote"} ${filePath}`);
  }

  return {
    pluginName: plugin.manifest.name,
    target: "cursor",
    filesWritten,
    portability: plugin.portability,
    warnings: plugin.warnings,
  };
}

/* ------------------------------------------------------------------ */
/*  Codex transformer                                                  */
/* ------------------------------------------------------------------ */

function buildCodexContent(plugin: ParsedPlugin): string {
  const attrs: Record<string, string> = {
    name: plugin.manifest.name,
    description: plugin.manifest.description || "",
  };

  const sections: string[] = [];
  sections.push(renderFrontmatter(attrs));
  sections.push(`# ${plugin.manifest.name}`);
  sections.push("");
  sections.push(`> ${MARKER} from anthropic/${plugin.manifest.name} plugin.`);
  sections.push("");

  if (plugin.manifest.description) {
    sections.push(plugin.manifest.description);
    sections.push("");
  }

  for (const cmd of plugin.commands) {
    sections.push(renderCommandSection(cmd));
  }

  for (const agent of plugin.agents) {
    sections.push(renderAgentSection(agent));
  }

  for (const skill of plugin.skills) {
    sections.push(renderSkillSection(skill));
  }

  sections.push(renderHookWarnings(plugin));

  return sections.join("\n");
}

async function transformForCodex(
  plugin: ParsedPlugin,
  outputDir: string,
  options: { verbose?: boolean; dryRun?: boolean },
): Promise<TransformResult> {
  const provider = getProvider("codex");
  const skillDir = join(outputDir, provider.skillsDir, plugin.manifest.name);
  const filePath = join(skillDir, "SKILL.md");
  const filesWritten: string[] = [];

  const content = buildCodexContent(plugin);

  if (!options.dryRun) {
    await mkdir(skillDir, { recursive: true });

    if (existsSync(filePath)) {
      const existing = await readFile(filePath, "utf-8");
      if (!existing.includes(MARKER)) {
        if (options.verbose) {
          console.log(`  Skipping ${filePath}: user-owned file`);
        }
        return {
          pluginName: plugin.manifest.name,
          target: "codex",
          filesWritten: [],
          portability: plugin.portability,
          warnings: [...plugin.warnings, "Skipped: existing user-owned file"],
        };
      }
    }

    await writeFile(filePath, content);
  }

  filesWritten.push(filePath);
  if (options.verbose) {
    console.log(`  ${options.dryRun ? "would write" : "wrote"} ${filePath}`);
  }

  return {
    pluginName: plugin.manifest.name,
    target: "codex",
    filesWritten,
    portability: plugin.portability,
    warnings: plugin.warnings,
  };
}

/* ------------------------------------------------------------------ */
/*  Claude transformer (validated copy)                                */
/* ------------------------------------------------------------------ */

async function transformForClaude(
  plugin: ParsedPlugin,
  outputDir: string,
  options: { verbose?: boolean; dryRun?: boolean },
): Promise<TransformResult> {
  const provider = getProvider("claude");
  const skillDir = join(outputDir, provider.skillsDir, plugin.manifest.name);
  const filePath = join(skillDir, "SKILL.md");
  const filesWritten: string[] = [];

  // For Claude, build a combined SKILL.md from the plugin's components
  const content = buildCodexContent(plugin); // Same markdown format works

  if (!options.dryRun) {
    await mkdir(skillDir, { recursive: true });

    if (existsSync(filePath)) {
      const existing = await readFile(filePath, "utf-8");
      if (!existing.includes(MARKER)) {
        if (options.verbose) {
          console.log(`  Skipping ${filePath}: user-owned file`);
        }
        return {
          pluginName: plugin.manifest.name,
          target: "claude",
          filesWritten: [],
          portability: plugin.portability,
          warnings: [...plugin.warnings, "Skipped: existing user-owned file"],
        };
      }
    }

    await writeFile(filePath, content);
  }

  filesWritten.push(filePath);
  if (options.verbose) {
    console.log(`  ${options.dryRun ? "would write" : "wrote"} ${filePath}`);
  }

  return {
    pluginName: plugin.manifest.name,
    target: "claude",
    filesWritten,
    portability: plugin.portability,
    warnings: plugin.warnings,
  };
}

/* ------------------------------------------------------------------ */
/*  Analysis (preview before writing)                                  */
/* ------------------------------------------------------------------ */

function resolveTargetFile(
  plugin: ParsedPlugin,
  target: ProviderName,
  outputDir: string,
): string {
  switch (target) {
    case "cursor":
      return join(outputDir, ".cursor", "rules", `${plugin.manifest.name}.md`);
    case "codex":
      return join(outputDir, getProvider("codex").skillsDir, plugin.manifest.name, "SKILL.md");
    case "claude":
      return join(outputDir, getProvider("claude").skillsDir, plugin.manifest.name, "SKILL.md");
    default:
      return join(outputDir, `${plugin.manifest.name}.md`);
  }
}

function determineAction(targetFile: string): FileAction {
  if (!existsSync(targetFile)) return "create";
  try {
    const content = readFileSync(targetFile, "utf-8");
    if (content.includes(MARKER)) return "update";
    return "skip (user-owned)";
  } catch {
    return "create";
  }
}

/**
 * Analyze what a transform would do without writing any files.
 * Returns a full breakdown of each plugin: what exists, what changes, warnings.
 */
export function analyzeTransform(
  plugins: ParsedPlugin[],
  target: ProviderName,
  outputDir: string,
): TransformAnalysis {
  const analyses: PluginAnalysis[] = [];
  let create = 0;
  let update = 0;
  let skip = 0;

  for (const plugin of plugins) {
    const targetFile = resolveTargetFile(plugin, target, outputDir);
    const action = determineAction(targetFile);

    if (action === "create") create++;
    else if (action === "update") update++;
    else skip++;

    analyses.push({
      pluginName: plugin.manifest.name,
      portability: plugin.portability,
      components: {
        commands: plugin.commands.length,
        agents: plugin.agents.length,
        skills: plugin.skills.length,
        hooks: plugin.hooks.length,
      },
      targetFile,
      action,
      warnings: plugin.warnings,
    });
  }

  return {
    target,
    outputDir,
    plugins: analyses,
    summary: {
      total: plugins.length,
      create,
      update,
      skip,
    },
  };
}

/**
 * Format an analysis as a human-readable string for CLI display.
 */
export function formatAnalysis(analysis: TransformAnalysis): string {
  const lines: string[] = [];

  lines.push("Analysis");
  lines.push("--------\n");
  lines.push(`Target:  ${getProvider(analysis.target).displayName} (${analysis.target})`);
  lines.push(`Output:  ${analysis.outputDir}`);
  lines.push(`Plugins: ${analysis.summary.total} found\n`);

  // Table header
  const nameWidth = Math.max(
    20,
    ...analysis.plugins.map((p) => p.pluginName.length),
  );
  lines.push(
    `  ${"Plugin".padEnd(nameWidth)}  ${"Portability".padEnd(11)}  ${"Components".padEnd(18)}  Action`,
  );
  lines.push(
    `  ${"─".repeat(nameWidth)}  ${"─".repeat(11)}  ${"─".repeat(18)}  ${"─".repeat(18)}`,
  );

  for (const p of analysis.plugins) {
    const comps: string[] = [];
    if (p.components.commands > 0) comps.push(`${p.components.commands} cmd`);
    if (p.components.agents > 0) comps.push(`${p.components.agents} agent`);
    if (p.components.skills > 0) comps.push(`${p.components.skills} skill`);
    if (p.components.hooks > 0) comps.push(`${p.components.hooks} hook`);
    const compStr = comps.join(", ") || "empty";

    const actionLabel =
      p.action === "create" ? "+ create" :
      p.action === "update" ? "~ update" :
      "- skip (user-owned)";

    lines.push(
      `  ${p.pluginName.padEnd(nameWidth)}  ${p.portability.padEnd(11)}  ${compStr.padEnd(18)}  ${actionLabel}`,
    );
  }

  lines.push("");

  // Summary
  const parts: string[] = [];
  if (analysis.summary.create > 0) parts.push(`${analysis.summary.create} new`);
  if (analysis.summary.update > 0) parts.push(`${analysis.summary.update} update`);
  if (analysis.summary.skip > 0) parts.push(`${analysis.summary.skip} skip`);
  lines.push(`Summary: ${parts.join(", ")}`);

  // Warnings
  const allWarnings = analysis.plugins.flatMap((p) =>
    p.warnings.map((w) => `  ${p.pluginName}: ${w}`),
  );
  if (allWarnings.length > 0) {
    lines.push("\nWarnings:");
    for (const w of allWarnings) {
      lines.push(w);
    }
  }

  lines.push("");
  return lines.join("\n");
}

/* ------------------------------------------------------------------ */
/*  Main entry point                                                   */
/* ------------------------------------------------------------------ */

export async function transformPlugin(
  plugin: ParsedPlugin,
  options: TransformOptions,
): Promise<TransformResult> {
  const outputDir = options.outputDir || process.cwd();

  switch (options.target) {
    case "cursor":
      return transformForCursor(plugin, outputDir, options);
    case "codex":
      return transformForCodex(plugin, outputDir, options);
    case "claude":
      return transformForClaude(plugin, outputDir, options);
    default:
      throw new Error(`Unsupported transform target: ${options.target}`);
  }
}

// Exported for testing
export { buildCursorContent, buildCodexContent, stripClaudeSpecificFrontmatter, resolveTargetFile, determineAction };
